### ISSUE TITLE
can we get colors from i3/config ?

### ISSUE THREAD

**Issue by aleprovencio** [i3/i3status#121]
I think this would be a good idea since the i3 theme colors are already defined on i3/config thus we would not have yet another file to put color information, what do you think?

**Comment by Airblader** [comment]
I think once https://github.com/i3/i3/issues/2130 is implemented we *could* consider taking default colors for i3status from Xresources as well (use-defined > Xresources > hard-coded defaults).

Extracting colors from the i3 config is the wrong way around, especially since, strictly speaking, i3status doesn't require i3 to be running or even installed.

**Comment by aleprovencio** [comment]
Absolutely true, I had not seen that issue.

**Comment by stapelberg** [comment]
Given that the i3 4.13 shipped with taking variables from Xresources, this issue is now unblocked.

However, I have to say that I don’t actually find it appealing to add 2 dependencies (xcb-util-xrm for Xresources parsing, and libxcb itself for connecting to X11) to i3status, just to support this use-case.

Rather, I’d recommend using a third-party tool/script which does that and generates a config file for i3status.

**Comment by Airblader** [comment]
Makes sense to me. Should we close this then?

**Comment by stapelberg** [comment]
Yes.
