### ISSUE TITLE
Monitor memory usage

### ISSUE THREAD

**Issue by lahwaacz** [i3/i3status#165]
The [story in the man page](https://github.com/i3/i3status/blob/8d2ef5f99b2ebc08a0a9d1f26492094692b1fc6b/man/i3status.man#L600-L611) is half user-specific and half false.

1. There are reasons why users might want to monitor memory usage. For example, I have 8 GB of memory and applications running most of the time in my session (e.g. browser) can easily take about 4 GB. Yet from time to time I need to compile a project which temporarily needs about 6 GB of memory. There is nothing easier than to look at the status bar to see if I need to close the browser or something.
2. The technical reasons regarding the difficulties of measuring memory usage don't apply anymore, at least on Linux, which does the hard work for us. i3status could just read the `MemTotal` and `MemAvailable` fields from `/proc/meminfo` and calculate a percentage. See [proc.txt](https://github.com/torvalds/linux/blob/1b5946a84d6eb096158e535bdb9bda06e7cdd941/Documentation/filesystems/proc.txt#L834-L961) in the kernel documentation.

**Comment by stapelberg** [comment]
1. When I run work loads which exceed my available memory, the OOM killer kills processes (corresponding to tabs) as necessary. Is that not what you’re seeing on your machine? I’m using Chrome, but I’m assuming that Firefox with [e10s](https://wiki.mozilla.org/Electrolysis) enabled should behave the same way. From a philosophical standpoint, I still think that you shouldn’t need to monitor memory usage and just let your OOM killer do what you would do manually.

2. Interesting, thanks for pointing that out! https://blog.famzah.net/2014/09/24/memavailable-metric-for-linux-kernels-before-3-14-in-procmeminfo/ says MemAvailable was introduced in Linux 3.14.

**Comment by Airblader** [comment]
For what it's worth, I support adding a memory output option. It's easily more relevant than displaying my ip address and I definitely think users may want to track it. Chrome may have an OOM but my private machine also has only 8 GB and running a VM and then some other things can cause this clash and often don't end nicely.

**Comment by lahwaacz** [comment]
@stapelberg OK, two more points:

I mentioned browser, but that's just an example. It also does not mean that there is just one dominant application running, in my case the 4 GB level most often consists of 2 browsers (Chromium and [qutebrowser](https://github.com/The-Compiler/qutebrowser/)) and 2 instances of [YouCompleteMe](https://github.com/Valloric/YouCompleteMe/) on heavily templatized C++ projects. Of these, only Chromium plays nice with the OOM killer and while qutebrowser is being ported to QtWebEngine, it's not quite there yet. Also, I don't like the OOM killer playing roulette to decide which of my running programs should be terminated.

As far as I know, the OOM killer is intended only as a last resort and not something users might depend on in the daily routine. On my system, there is a period of several minutes between I run out of memory and the OOM killer kills something, and the system is "frozen" in the meantime. Is it normal or some misconfiguration on my part that I might be unaware of?

**Comment by stapelberg** [comment]
> Also, I don't like the OOM killer playing roulette to decide which of my running programs should be terminated.

The OOM killer has a documented algorithm, it’s far from roulette :).

> On my system, there is a period of several minutes between I run out of memory and the OOM killer kills something, and the system is "frozen" in the meantime. Is it normal or some misconfiguration on my part that I might be unaware of?

That sounds like a misconfiguration. You’re sure you don’t have swap space enabled, are you?

**Comment by lahwaacz** [comment]
> The OOM killer has a documented algorithm, it’s far from roulette :).

Is it at least deterministic? Even if it is, the result is basically the same since it takes non-deterministic data as input. Let's say for simplicity that it always kills the program which currently takes most of the memory - then it may kill _foo_ tomorrow while it was _bar_ yesterday and the user would rather always sacrifice _baz_ instead.

> You’re sure you don’t have swap space enabled, are you?

Yes, there is no swap on my system.

**Comment by stapelberg** [comment]
> Is it at least deterministic? Even if it is, the result is basically the same since it takes non-deterministic data as input. Let's say for simplicity that it always kills the program which currently takes most of the memory - then it may kill foo tomorrow while it was bar yesterday and the user would rather always sacrifice baz instead.

Yes, it’s a deterministic algorithm.

Users can influence the algorithm using the oom_adj file. Please see e.g. https://unix.stackexchange.com/questions/153585/how-oom-killer-decides-which-process-to-kill-first and http://www.oracle.com/technetwork/articles/servers-storage-dev/oom-killer-1911807.html for details.

I’m not entirely sure about why you’re seeing the odd behavior. Perhaps you can post a question about that e.g. on stackexchange and refer to it here?

**Comment by yidolim** [comment]
@lahwaacz There are plenty of alternatives out there, if one program doesn't provide the features requested by you, then move along and try something different , for example - https://gitlab.com/void0/pinky-bar

**Comment by Airblader** [comment]
Note that you don't need to move away from i3bar, you can also just exchange i3status for something like i3blocks.

**Comment by lahwaacz** [comment]
@stapelberg Do you agree that I should move away from your personal tool or would you rather admit that relying on the OOM killer is not the best way for everybody and be fine with something like [this](https://github.com/lahwaacz/i3status/commit/0be144b8b86ee1886ed2c7b8428fb5e50d51ddbc) added to i3status? I will happily stop wasting our time if you still stand by the story from the man page.

**Comment by stapelberg** [comment]
> Do you agree that I should move away from your personal tool

Use whichever tool works best for you.

> or would you rather admit that relying on the OOM killer is not the best way for everybody and be fine with something like this added to i3status?

I don’t like the way you phrase this question.

To clarify, I’m not saying everybody must use the OOM killer and be happy with that. I’m saying that the i3status philosophy favors relying on the OOM killer over constantly monitoring available memory and manually replacing the OOM killer’s functionality.

We use this philosophy to guide what we add to the software and what we don’t, in an effort to prevent the software from becoming too bloated. This worked relatively well for us so far, but one of the effects we have to accept is that not everybody is 100% happy with our software.

Closing this issue to reflect the above decision in the status.

**Comment by mredaelli** [comment]
Somewhat later...
I read the discussion in #221 and here, and I actually think that these points were not really addressed:
- RAM is certainly more interesting than my ip address
- in reality, the OOM killer doesn't always solve the problems, or if it does, it might take time and decisions you don't like
- crucially, the OOM killer comes into the picture *after* the problem has occurred, while having the metric displayed is a way to *prevent* the problem to ever happen. Which is why me checking this metric before, say, starting a VM is *not* replacing the OOM killer functionality.
- the man page should at least be updated, removing the reference to not there being a good metric for memory usage

I would very much welcome the addition of this metric, especially since it seems to have been coded already by @lahwaacz, and maybe @flammi , and it certainly doesn't look like bloat to me :)
If still the decision doesn't change, question for @Airblader : can you hint about some of the other ways to get the metric, other than the solution outlined in the man page (which is a bit against the whole idea of " it saves a bit of energy by not hogging your CPU as much as spawning the corresponding amount of shell commands would")?

**Comment by Airblader** [comment]
> can you hint about some of the other ways to get the metric

You'd have to just exchange i3status for another tool such as i3blocks (or whichever). As I said above, I myself am in support of adding a memory module.

**Comment by flammi** [comment]
@mredaelli I had basically the same thoughts when I opened #221. I ended up with using i3pystatus, however I am not 100 percent as I have the feeling that i3status is more mature and overall a really good piece of software... I thought about forking i3status and and add a few features, but then ended up using pyi3status because I had not enough time...

**Comment by Stunkymonkey** [comment]
> You'd have to just exchange i3status for another tool such as i3blocks (or whichever). As I said above, I myself am in support of adding a memory module.

then why did you close #270 ?

From the wiki:
> Let’s talk about memory usage specifically. It is hard to measure memory in a way which is accurate or meaningful. An in-depth understanding of how paging and virtual memory work in your operating system is required. 

We don't support it, because its to complicated. See #270 . Its already done

> Furthermore, even if we had a well-defined way of displaying memory usage and you would understand it, I think that it’s not helpful to repeatedly monitor your memory usage.

I believe having a red "symbol" in the bar when your computer is running low on ram is very helpful. Specially if you do not have swap enabled

> One reason for that is that I have not run out of memory in the last few years.  Memory has become so cheap that even in my 4 year old notebook, I have 8 GiB of RAM. 

That is an "works for me" excuse, which is a problem of open source. If it only works for you, it is still not suitable for many others. There are some user, who are not able to upgrade the memory easily (e.g. because the ram is soldered, or raspberry, ...).

> Another reason is that your operating system will do the right thing anyway: Either you have not enough RAM for your workload, but you need to do it anyway, then your operating system will swap.

A lot of people do not like having swap on an ssd, because it will reduce the lifetime of the ssd.

> Or you don’t have enough RAM and you want to restrict your workload so that it fits, then the operating system will kill the process using too much RAM and you can act accordingly.

I got stuck a few times this year. Because while programming, the programmer does not want to care about memory at all. And mistakes will occur, so it would be great to prevent your computer in getting stuck

> In general, i3status wants to display things which you would look at occasionally anyways, like the current date/time, whether you are connected to a WiFi network or not, and if you have enough disk space to fit that 4.3 GiB download.

Having enough disk-space seems for me the same like having ram. You could also argue, that you can just buy a bigger disk...

For me the best argument in this thread was always, that it is to much work. But now it did some work in #270 . The PR is definitely not ready for merging! There are unfinished things, like testing, BSD-support, ...

My question: When the PR would be ready to merge, will it get merged?

**Comment by Airblader** [comment]
> then why did you close #270 ?

Because while I support it, @stapelberg has made it clear in the past that he doesn't want to add it to i3status and as the owner of the project, I respect his decision.

All the arguments are fine with me, so maybe @stapelberg can chime in again and either change his mind or make a once-and-for-all kind of decision. :-)

**Comment by stapelberg** [comment]
I still don’t think people should manually observe implementation details like the current memory usage, but as it’s clearly important enough to some users that we’re still having this discussion after many years, I won’t object to adding it anymore.

**Comment by BigET** [comment]
I also want to use i3 and i3status. But for me seeing the memory usage is very important.
So Important that I will take the initial memory-usage support from the fork and not use i3status master, hope it will be merged soon.
Consider this. I am a software developer. My long running software can have memory leaks that could eat up memory very quickly and in spikes.
Let me tell you how a Linux system will work when you do not have RAM and the SWAP kicks in.
It becomes non-responsive. The offending process can just about outrun the swapping i/o process.
The mouse will almost not work.
Even starting of an xterm to kill the process will take literary minutes.
Consider that your HDD does real 100MB/s. A SWAP of 20GB means that will almost freeze your system for 200 second.
These are real stories on recent Ubuntu system.
My 2 cents.

**Comment by Airblader** [comment]
I appreciate the feedback, but we don't need to keep arguing in favor of a change that has been approved already.

**Comment by hasufell** [comment]
> I still don’t think people should manually observe implementation details like the current memory usage

Sure, the issue has been resolved, but out of curiosity, this is still a very confusing kind of argument.

1. why would you think people should or should not observe an implementation detail like current memory usage. That sounds a little patronizing like "buy more ram"
2. how is cpu usage, wireless connectivity, free disk space and... especially date not an implementation detail?

**Comment by stapelberg** [comment]
> how is cpu usage, battery state, wireless connectivity, free disk space and... especially date not an implementation detail?

Adding CPU usage was a mistake, but I didn’t realize it at the time.

Disk space and wireless connectivity are different from RAM in that they are not typically automatically reclaimed: for disk space, you might need to delete some files. For wireless connectivity, you might need to physically move someplace else. For RAM, there’s no need to do anything: we have the OOM killer.

In the same spirit, I don’t believe in memory optimizers or memory managers on smart phones.

Anyway, as Airblader outlined, there’s no need to debate this anymore, so this will be my final comment on the topic.
