### ISSUE TITLE
Remove wireless attribute padding?

### ISSUE THREAD

**Issue by jbernard** [i3/i3status#166]
Hallo, I removed the right-justification / padding in the wireless attributes such that leading 0's are no longer printed and I find the result to be quite pleasing.  I suspect there is a reason for not doing this earlier (consistent widths perhaps) but I wanted to suggest the change anyway just in case:

https://github.com/jbernard/i3status/commit/4d21a18599538292eb29acd3189c354e21acd2da

If there is interest, I'm happy to rebase and submit a pull request.

**Comment by stapelberg** [comment]
The `%03d` format string was introduced in commit 71f71660322b12b8602f5979222d280b7db333bd in 2010. The rationale is to have the width fixed, so that the different status modules don’t jump around when your wireless signal changes.

Entirely removing the padding does not seem like something we’d want to do, but using `%3d` instead of `%03d` (i.e. blank-padded instead of zero-padded) should be fine. If you’re interested in that, please send a pull request.

**Comment by devkev** [comment]
Should this be closed, since the fix was merged in #167?

**Comment by Airblader** [comment]
Yes, thanks!
