### ISSUE TITLE
Hide unit of disk space

### ISSUE THREAD

**Issue by danijar** [i3/i3status#212]
I'd like to print the available disk space in GiB as plain number without the unit name. Is this currently possible or could be made available in the future?

**Comment by eplanet** [comment]
I think it isn't currently possible. The best you can do is define `prefix_type = custom` in your configuration, that would display `GB` instead of `GiB`. [More info here](https://github.com/i3/i3status/blob/master/man/i3status.man#L229).

**Comment by eplanet** [comment]
@stapelberg @Airblader: what do you think of that feature? Is it worth adding `prefix_type = no_unit`?

**Comment by stapelberg** [comment]
The only place that I can find where we separate the value from the unit is the cpu_temperature, which would have been removed from i3status if we didn’t strive to guarantee backwards-compatibility.

Hence, there’s no strong argument to be made for consistency, and I’m not convinced saving the two characters (“GB”) outweighs the additional complexity.

Additionally, consider how the lack of a unit might be significantly misleading once your available disk space drops into a different unit: you might be wondering why that 600 MB installer image doesn’t fit, even though you have “10” available (10 MB instead of 10 GB).

I think it’s better to reject this feature request. If people feel strongly, they can always filter i3status’s output.

**Comment by danijar** [comment]
Thanks, I agree.
