### ISSUE TITLE
Can't parse axp288_fuel_gauge uevent

### ISSUE THREAD

**Issue by danielotero** [i3/i3status#215]
I have an Intel Atom table with a AXP288 PMIC that reports the battery information in the following way:
```
/sys/class/power_supply/axp288_fuel_gauge/uevent:

POWER_SUPPLY_NAME=axp288_fuel_gauge
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_HEALTH=Good
POWER_SUPPLY_VOLTAGE_MAX_DESIGN=4200000
POWER_SUPPLY_VOLTAGE_NOW=3872000
POWER_SUPPLY_VOLTAGE_OCV=3942000
POWER_SUPPLY_CURRENT_NOW=-928000
POWER_SUPPLY_CAPACITY=75
POWER_SUPPLY_CAPACITY_ALERT_MIN=0
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CHARGE_FULL=6404944
POWER_SUPPLY_CHARGE_NOW=4816448
```

This causes that batt_info (at [this](https://github.com/i3/i3status/blob/94651257cea4ff419f9cf2143d93193d5a5ccb96/src/print_battery_info.c#L179) point) to be:
```
{ full_design = -3,
  full_last = 25133000,
  remaining = 20505191,
  present_rate = 3327552,
  seconds_remaining = -1,
  percentage_remaining = -1,
  status = CS_DISCHARGING }
```
Which then causes the code to go through [this](https://github.com/i3/i3status/blob/94651257cea4ff419f9cf2143d93193d5a5ccb96/src/print_battery_info.c#L502) path, that causes a "No battery" result.

Can't this be done in a better way?

**Comment by eplanet** [comment]
This is totally linked to #214. Just wait for the PR #216 to be merged, and `POWER_SUPPLY_CAPACITY` will be exploited to display correct percentage.

**Comment by itdaniher** [comment]
Ran into this issue with an AXP803 on my pinebook using an old build of i3status in Ubuntu 16.04. Happy to say this fixes the issue for me!

**Comment by eplanet** [comment]
Great! Thanks for sharing @itdaniher

**Comment by eplanet** [comment]
@danielotero could you confirm that it fixes the issue for you and possibly close it?

**Comment by danielotero** [comment]
Sorry about the delay, I almost forgot about this issue. 

Soon after this issue I managed to put `last_full_capacity=true` in the battery section (don't remember where I did get that option from) to get rid of the "No battery" message.

I just build from source the last master branch (including the commit from #216) and it seems to have no effect on this bug report.

I don't mind closing this bug report if the "No battery" message is the expected behavior from the input in the first place.

**Comment by kousu** [comment]
I have this device and the same issue with i3 on a [baytrail tablet](https://github.com/burzumishi/linux-baytrail-flexx10).

I pulled the latest code just now (before I found this issue) and it showed no change.
My config is

```
battery 0 {
        format = "%status %percentage %remaining"
        format = "%percentage"
        path = "/sys/class/power_supply/axp288_fuel_gauge/uevent"
}
```

I hunted the problem down to [the exact same line]
(https://github.com/i3/i3status/blob/ca9bee8b885e810fd849abcb9b544b487636854c/src/print_battery_info.c#L502) as @danielotero found, and even observed `batt_info.full_design = -3`

```
    int full = (last_full_capacity ? batt_info.full_last : );
    if (full < 0 && batt_info.percentage_remaining < 0) {
        /* We have no physical measurements and no estimates. Nothing
         * much we can report, then. */
        OUTPUT_FULL_TEXT(format_down);
        return;
    }
```

Because the default config file came without `last_full_capacity = true` set the -3 fails the check on the next line. That comment needs to be changed, and maybe the overall logic too, since we *do* have a physical measurement, we're just ignoring it.

Do you think maybe the "No Battery" output should be changed here to something like "error reading battery"? I was assuming for a long time that "No Battery" meant I hadn't given the right path, and then after I had given the right path, I was assuming it meant I had given the wrong path or the path was the wrong filetype or something.


Speaking of that -3, it's coming from [L181](https://github.com/i3/i3status/blob/ca9bee8b885e810fd849abcb9b544b487636854c/src/print_battery_info.c#L181):
```
if (!watt_as_unit && voltage != -1) {
        batt_info->present_rate = (((float)voltage / 1000.0) * ((float)batt_info->present_rate / 1000.0));
        batt_info->remaining = (((float)voltage / 1000.0) * ((float)batt_info->remaining / 1000.0));
        batt_info->full_design = (((float)voltage / 1000.0) * ((float)batt_info->full_design / 1000.0));
        batt_info->full_last = (((float)voltage / 1000.0) * ((float)batt_info->full_last / 1000.0));
    }
```
would it be better if that section only updated the valid (i.e. nonnegative) values?

**Comment by kousu** [comment]
Another weirdness is that even though uevent directly says `POWER_SUPPLY_CAPACITY=75` and all I want is i3status to output that number, there's this complicated logic

```
        if (BEGINS_WITH(last, "POWER_SUPPLY_ENERGY_NOW=")) {
            watt_as_unit = true;
            batt_info->remaining = atoi(walk + 1);
            batt_info->percentage_remaining = -1;
        } else if (BEGINS_WITH(last, "POWER_SUPPLY_CHARGE_NOW=")) {
            watt_as_unit = false;
            batt_info->remaining = atoi(walk + 1);
            batt_info->percentage_remaining = -1;
        } else if (BEGINS_WITH(last, "POWER_SUPPLY_CAPACITY=") && batt_info->remaining == -1) {
            batt_info->percentage_remaining = atoi(walk + 1);
        }
```

which says implicitly that whichever of `POWER_SUPPLY_ENERGY_NOW`, `POWER_SUPPLY_CHARGE_NOW` and `POWER_SUPPLY_CAPACITY` is last wins, and only one of `percentage_remaining` and `remaining` can be valid at once. I'd expect we'd slurp in whatever info the driver chooses to give.

And in light of that, why does `if (full < 0 && batt_info.percentage_remaining < 0) {` only look at one of them? Shouldn't it say something like `if(full < 0 && batt_info.remaining < 0 && batt_info.percentage_remaining < 0)`?
