### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by eplanet** [i3/i3status#217]
Wouldn't it be nice to add bash completion to i3status? I know this would both be rarely used and only by a few people, but I personally would love it :stuck_out_tongue_closed_eyes:.

I'd be happy to propose a PR adding that.

**Comment by Airblader** [comment]
i3status has like three command-line arguments. What's the point of a completion for that?

**Comment by eplanet** [comment]
Looks like an additional reason to add it if there's not much work. I'm sure some people would like it. But that's up to you to decide!

**Comment by Airblader** [comment]
I fail to see why auto-completing one-character command-line options would be useful.

**Comment by eplanet** [comment]
That's because there's `--run-once` as well, that I use very often. And completing one-character could be useful to me: you don't have to run help to get instant glance of available arguments. But I'd understand if you're not convinced…

By the way, the same applies to `i3lock`, that have a lot more command-line argument.

**Comment by Airblader** [comment]
> you don't have to run help to get instant glance of available arguments

Yes, but the only other ones are `-h`, `-v` and `-c`. Again, doesn't seem that useful to me. That leaves `--run-once`, but I just don't really see much of a benefit in maintaining this here, particularly since there's more shells than just bash; adding it for one means other people will want it for others etc.

I think it's very reasonable to say i3status (and i3lock, for that matter) aren't tool we expect to be run manually from the command-line. And as far the i3 IPC goes, we already have [this](https://github.com/i3/i3/issues/1738).

For these reasons I think we should stay away from having this in the repository itself; of course you can always provide such completions separately :-) I assume you mostly need `--run-once` for development reasons anyway, correct? So you could also have a local alias like `alias i3statusro=i3status --run-once`.

**Comment by eplanet** [comment]
I must say you are very convincing… Let's say I'll put my `/etc/bash_completion.d/i3status` on my machine only, and I'll be happy :-P. Thanks for sharing your thoughts.
