### ISSUE TITLE
Stop discriminating IPv6

### ISSUE THREAD

**Issue by telmich** [i3/i3status#240]
When running i3status and being in an IPv6 only network, i3status shows:

W: ( ... ) no IP

Having

order += "wireless wlp2s0"
order += "ipv6"

in my i3status.conf, I do see the IPv6 address in the next field. However seeing "no IP" next to it, simply does not make sense in the age of IPv6. There is an IP. A better than IPv4 IP address even!

I am aware that this is a bit like "Use Windows NT or better - so I used Linux" bug report, however I think it is time to fix the sentiment at the base of our hearts. IPv6 is here, IPv6 is not a second, but a first class citizen.

I suggest to

a) rephrase "no IP" to "no IPv4"
b) include IPv6 into the wireless block
c) OR exclude IPv4 from the wireless block

I think c) is not that feasible (breaking existing user), however I think b) is feasible if we exclude the link local address.

Btw, thanks for the simple status bar - it's really nice to use!

Output of i3 --moreversion 2>&- || i3 --version:

Binary i3 version: 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 24983) abort…)
Loaded i3 config: /home/nico/.i3/config (Last modified: Thu 03 Aug 2017 06:01:08 PM CEST, 2047424 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by eplanet** [comment]
Well I'd say that IPv4 is far from dead and will endure for quite a long time, if not forever. I even personally prefer it, since it's less verbose and a lot easier to memorize / input.

That being said, I agree that when no IPv4 is available but an IPv6 is, it should be displayed (you "solution b"). Do you intend to propose a PR for that?

**Comment by telmich** [comment]
After knowing which direction to go, I will have a look at the code and submit a PR soon!

**Comment by eplanet** [comment]
Will wait for @stapelberg and @Airblader insights then.

**Comment by stapelberg** [comment]
Note that the ipv6 module does something different: it displays whether you have an IPv6 address with global connectivity (by creating a connectionless UDP socket and obtaining the local address).

Displaying the most important IPv6 address when an interface doesn’t have an IPv4 address sounds good to me.

I think we should implement that with a new format string though, and then change the default config, so that existing users aren’t surprised by the new behavior.

**Comment by eplanet** [comment]
@telmich #247 has been merged, could you try with latest master and confirms it works in your environment? Thanks!

**Comment by telmich** [comment]
Tested, works like charm! Thanks a lot! Welcome world of IPv6!

**Comment by eplanet** [comment]
Thanks for testing so rapidly! I suppose you can close the issue then ;-).
