### ISSUE TITLE
Use format_not_mounted for missing mount points

### ISSUE THREAD

**Issue by ambihelical** [i3/i3status#33]
I'd like to set up a disk module entry for a particular thumb drive I occasionally use.  The underlying OS (mint 17.1) dynamically mounts this drive to /media/_uid_/_volname_, and only the directory /media exists before drive is mounted. 

If I set up a disk module entry for the mount point of this drive, i3status does not do nice things when the drive is not mounted because the mount directory doesn't exist.  The display output is "SPEC VIOLATION: full_text is NULL!".  Looking at i3status output, full_text is indeed missing. 
In the code it appears that a failed stat on the mount point causes an early exit even when format_not_mounted is defined. 

It would be better if i3status interpreted a missing directory as a non-mounted drive instead and used the format_not_mounted format instead of erroring out.

**Comment by Airblader** [comment]
According to http://i3wm.org/i3status/manpage.html#_disk there is a `format_not_mounted`. Does this work for you?

**Comment by Airblader** [comment]
Sorry, excuse my previous comment, I clearly wasn't fully awake yet. :) The issue is that [this](https://github.com/i3/i3status/blob/master/src/print_disk_info.c#L127) returns since nothing could be read which happens before `format_not_mounted` is even considered.

@stapelberg I think it's reasonable to use `format_not_mounted` if the directory doesn't exist. What do you think?

**Comment by stapelberg** [comment]
Agreed.

**Comment by Airblader** [comment]
Alright. I'll prepare a PR.

**Comment by Airblader** [comment]
@ambihelical The patch has been merged. Though I tested it for myself, feedback that it works for you as well is appreciated. :)

**Comment by ambihelical** [comment]
works great!
