### ISSUE TITLE
Commit 668bf207 (nl80211 wireless) partially misattributes code origins

### ISSUE THREAD

**Issue by amonakov** [i3/i3status#65]
Commit 668bf207 appears to lift code from the NetworkManager, without acknowledging that in the commit message. Function `find_ssid` appears to be copied verbatim: [NM code](https://github.com/NetworkManager/NetworkManager/blob/2318c0de9291b9dcf9e720a2e5041266449dfd57/src/platform/wifi/wifi-utils-nl80211.c#L310-L328) vs [i3status code](https://github.com/i3/i3status/blob/668bf2079f30e5df8f78974ebee2194d873f50ac/src/print_wireless_info.c#L118-L133), the preceding `nl80211_xbm_to_percent` function appears to be copied with a minor change.

Since the commit message only references my cr.i3wm.org submission, it may imply (to a reader that does not check the original) that the NetworkManager snippets already were in the patch that I submitted. That is not nice. I was actually careful to write original code suitable for use in BSD-licensed i3status rather than copying GPL'ed snippets.

Furthermore, I wonder how it is ok to use code originating from a GPLv2 project in i3status in the first place.

**Comment by stapelberg** [comment]
I didn’t mean to imply that you copied any code around without thinking, and I think my wording “based on” doesn’t imply that. My apologies for how it came across.

I think `nl80211_xbm_to_percent` is a fairly idiomatic way of expressing the algorithm at hand, i.e. if I were to rewrite that function, it would look pretty much the same. I didn’t change variable and constant names so that people can more easily compare the code between NetworkManager and i3status when they’re looking into a bug.

For `find_ssid`, it’s not as clear cut. I’m willing to accept patches that implement that code in a different fashion, but again, I think it’d be a bottomline-win for open source if the code stays easily identifiable as doing the same thing.

I don’t want to spend much time arguing about licensing, especially given that neither of us seems to be an expert on the subject. If you really still feel that this is a problem, please send a PR to replace the offending code. Thanks!

**Comment by amonakov** [comment]
It would be better if the commit message said "based on patch X from Y and NetworkManager code". I don't understand why you highlighted one contributing party, but not the other.

Can you please at least make a follow-up commit adding comments in the source code to mark functions that came from NM? Those two functions were easy to identify, but as for the rest of the patch — I guess only you now know what came from where.
