### ISSUE TITLE
Mobile Broadband

### ISSUE THREAD

**Issue by Fale** [i3/i3status#85]
As far as I have seen is not possible to visualize mobile broadband connections as it's possible to do with wired and wireless ones. I think it would be a nice feature to have :)

**Comment by stapelberg** [comment]
Here are a couple of thoughts:

* How is a mobile broadband connection different from just an ethernet connection? I.e., which information would you want to display aside from the IP address?
* Why is this use-case not already covered by what NetworkManager (or similar tools) display?
* Mobile broadband is certainly a feature which is not going to be used by the majority of i3status users. I think a far more common case is people using tethering with their mobile phones, hence just using a wireless or USB connection as far as the computer is concerned. I’m thinking it might make sense to put this into contrib/ instead of core i3status.

**Comment by Fale** [comment]
On Sat, Dec 05, 2015 at 02:55:43AM -0800, Michael Stapelberg wrote:
> Here are a couple of thoughts:
> 
> * How is a mobile broadband connection different from just an ethernet connection? I.e., which information would you want to display aside from the IP address?

Not very, but I tried to trick i3status to believe that the mobile
network is an eth, but something did not went according to plan.
I think is somehow more similar to a wireless connection than to a wired
one (ie: it has the signal strength).

> * Why is this use-case not already covered by what NetworkManager (or similar tools) display?

Gnome's network manager allows me to manage the mobile link, but does
not display it in i3status bar.

> * Mobile broadband is certainly a feature which is not going to be used by the majority of i3status users. I think a far more common case is people using tethering with their mobile phones, hence just using a wireless or USB connection as far as the computer is concerned. I’m thinking it might make sense to put this into contrib/ instead of core i3status.

Surely is not a feature that 100% of users will use since, as you said,
most people use tethering with their mobile phones

**Comment by stapelberg** [comment]
> I tried to trick i3status to believe that the mobile network is an eth, but something did not went according to plan.

Can you be more specific about what happened here? I.e. what did you expect, what did you see instead? Can you provide an strace log of i3status? (use `strace -f -tt -o /tmp/strace.log -s 2048 i3status`, cancel after a couple of seconds using Ctrl-C, then provide /tmp/strace.log, possibly compressed).

**Comment by Fale** [comment]
My .i3status.conf files has the following entries for networkign stuff:

    wireless _first_ {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
    }
    
    ethernet _first_ {
        # if you use %speed, i3status requires root privileges
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
    }
    
    wireless wwp0s20u4 {
        format_up = "M: %quality (%ip)"
        format_down = "M: down"
    }

The first two entries come by default (I don't know if it's i3status default or Fedora default), while I added the third to have the Mobile Broadband showed as well.

As for the strace, I'm not able to attach it (since the gz format is not accepted by github -.-) so you can find it at https://fale.fedorapeople.org/strace.log.gz

**Comment by stapelberg** [comment]
In the strace log file you provided, the wireless block you added is not actually referenced in your `/home/fale/.i3status.conf`, but commented out:

```
order += \"wireless _first_\" 
#order += \"wireless wwp0s20u4\"
order += \"ethernet _first_\"
order += \"battery 0\"
[…]
```

Can you provide a new strace log after fixing your config? Also, can you describe what you see and what you expect?

**Comment by Fale** [comment]
Sorry

This is what I'm seeing
![2015-12-10-165235_676x67_scrot](https://cloud.githubusercontent.com/assets/77888/11720224/a48848be-9f5e-11e5-8e30-6dd8936529ab.png)

I was expecting the Mobile connection to be green, since I'm currently connected with it.

Attaching the strace.zip file
[strace.zip](https://github.com/i3/i3status/files/58300/strace.zip)

**Comment by tnnn** [comment]
I'm using i3status with both internal 3G modem and external 3G USB tethering (through Android device). If I am not connected through my wired (twisted pair) interface, they are both reported as ethernet links (using 'ethernet _first_' directive). Even my VPN tunnel is reported through 'ethernet _first_' option.

**Comment by Fale** [comment]
@tnnn I use very rarely the wired connection, but what you are describing never happened to me

**Comment by stapelberg** [comment]
@Fale You’re using “wireless wwp0s20u4”, but you should be using “ethernet wwp0s20u4”. Wireless is for 802.11 devices, and mobile broadband is an ethernet device to the Linux kernel.

**Comment by Fale** [comment]
Thanks :) It did work.

**Comment by 151henry151** [comment]
This still doesn't allow mobile broadband users to see 3G connection strength... it is more like a wireless connection than it is like an ethernet connection

**Comment by kamazeuci** [comment]
I followed the instructions in this thread to get i3status to show me info about my `wwp0s20u4` mobile broadband connection. And, yes, it works, but I can only get the IP. Apparently, you can't get the speed, even if you add the privileges using `setcap` (although this function appears to be obsolete since 2011).
More information here:
[https://www.reddit.com/r/i3wm/comments/b7h809/i3status_not_showing_speed_for_mobile_broadband/
](url) 
Does anybody have an idea of how to show the mobile broadband module download/upload speed on any i3 status bar?

thanks
